import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,600;0,700;1,800&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="font-poppins">
        <Header />
        {children}
      </body>
    </html>
  );
}
